strictness: veryhigh
max-line-length: 99

pylint:
  disable:
    - too-few-public-methods
    - no-self-argument
    - arguments-differ
    # the focalcrop route makes it hard to lint too-many-arguments
    - too-many-arguments

pep8:
  full: true
  disable:
    - N805

ignore-paths:
  - terraform
  - scripts
