strictness: veryhigh
max-line-length: 99

pylint:
  disable:
    - arguments-differ
    # the focalcrop route makes it hard to lint too-many-arguments
    - too-many-arguments
    - useless-object-inheritance

pep8:
  full: true
  disable:
    - N805

ignore-paths:
  - terraform
  - scripts
